image:
- Visual Studio 2013
- Visual Studio 2015
- Visual Studio 2017
- Visual Studio 2019

for:
- matrix:
    only:
    - image: Visual Studio 2013
  build_script:
  - mkdir build10
  - cd build10
  - cmake .. -G "Visual Studio 10 2010"
  - cmake --build .
  - Debug\units.exe
  - cd ..
  - cd build12
  - cmake .. -G "Visual Studio 11 2012"
  - cmake --build .
  - Debug\units.exe
  - cd ..
  - mkdir build13
  - cd build13
  - cmake .. -G "Visual Studio 12 2013"
  - cmake --build .
  - Debug\units.exe
- matrix:
    only:
    - image: Visual Studio 2015
  build_script:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 14 2015"
  - cmake --build .
  - Debug\units.exe
- matrix:
    only:
    - image: Visual Studio 2017
  build_script:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 15 2017"
  - cmake --build .
  - Debug\units.exe
- matrix:
    only:
    - image: Visual Studio 2019
  build_script:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 16 2019"
  - cmake --build .
  - Debug\units.exe
