language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode10.1

#FIXME: Homebrew is out of date on Travis. Uncomment when it has CMake 3.13.
#addons:
# homebrew:
#   packages:
#     - cmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade cmake; fi

script:
  - mkdir build
  - cd build
  - which cmake
  - cmake ..
  - cmake --build .
