# Build matrix: https://docs.travis-ci.com/user/build-matrix/
# macOS Environments: https://docs.travis-ci.com/user/reference/osx/

language: cpp
os: osx

_null_cmake: &null_cmake
  script:
  - curl -sL https://github.com/Kitware/CMake/releases/download/v3.8.0/cmake-3.8.0-Darwin-x86_64.tar.gz | tar xz
  - mkdir build && cd build
  - ../cmake-3.8.0-Darwin-x86_64/CMake.app/Contents/bin/cmake ..
  - make

_null: &null
  script:
  - mkdir build && cd build
  - cmake ..
  - make

_sdl2: &sdl2
 addons:
   homebrew:
     packages:
     - sdl2
     - sdl2_image
     - sdl2_mixer
     update: true
 env:
 - LDFLAGS=-L/usr/local/lib
 script:
 - mkdir build && cd build
 - cmake .. -DAV_SDL2=On
 - make

jobs:
  include:
  - name: 10.11 null
    osx_image: xcode7.3
    <<: *null_cmake
  - name: 10.15 null
    osx_image: xcode12.2
    <<: *null
  - name: 10.13 sdl2
    osx_image: xcode10.1
    <<: *sdl2
  - name: 10.15 sdl2
    osx_image: xcode12.2
    <<: *sdl2
