# macOS Environments: https://docs.travis-ci.com/user/reference/osx/

language: cpp

os: osx
osx_image:
  - xcode7.3
  - xcode12

matrix:
  include:
    - script:
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build .
    - addons:
        homebrew:
          packages:
            - sdl2
            - sdl2_image
            - sdl2_mixer
          update: true
      script:
        - mkdir build
        - cd build
        - cmake .. -DAV_SDL2=On
        - cmake --build .
    - addons:
        homebrew:
          packages:
            - libgosu
          update: true
      env:
        - LDFLAGS=-L/usr/local/lib
      script:
        - mkdir build
        - cd build
        - cmake .. -DAV_GOSU=On
        - cmake --build .
