# Build matrix: https://docs.travis-ci.com/user/build-matrix/
# macOS Environments: https://docs.travis-ci.com/user/reference/osx/

language: cpp
os: osx

_null: &null
  script:
  - mkdir build && cd build
  - cmake ..
  - make

_sdl2: &sdl2
 addons:
   homebrew:
     packages:
     - sdl2
     - sdl2_image
     - sdl2_mixer
     update: true
 env:
 - LDFLAGS=-L/usr/local/lib
 script:
 - mkdir build && cd build
 - cmake .. -DAV_SDL2=On
 - make

jobs:
  include:
  - name: 10.11 null
    osx_image: xcode8.3
    <<: *null
  - name: 10.15 null
    osx_image: xcode12
    <<: *null
  - name: 10.13 sdl2
    osx_image: xcode10.1
    <<: *sdl2
  - name: 10.15 sdl2
    osx_image: xcode12
    <<: *sdl2
