language: cpp

os: osx
osx_image: xcode10.2

matrix:
  include:
    - script:
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build .
    - addons:
       homebrew:
         packages:
           - sdl2
           - sdl2_image
           - sdl2_mixer
      script:
        - mkdir build
        - cd build
        - cmake .. -DAV_SDL2=On
        - cmake --build .
