language: cpp

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - sourceline: "deb http://mirrors.kernel.org/ubuntu/ disco main"
    packages:
      - cmake
  homebrew:
    packages:
      - cmake

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
