language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx

addons:
  apt:
    sources:
      - sourceline: "deb http://ftp.debian.org/debian stretch-backports main"
    packages:
      - cmake
# FIXME: Homebrew is out of date on Travis. Uncomment when it has CMake 3.13.
# homebrew:
#   packages:
#     - cmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade cmake; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
