version: 2.1

jobs:
  debian_8_jessie:
    docker:
      - image: debian:8-slim
    steps:
      - run: |
          apt-get update &&
          apt-get install -y --no-install-recommends ca-certificates curl g++ ninja-build &&
          (cd /opt; curl -L https://github.com/Kitware/CMake/releases/download/v3.8.0/cmake-3.8.0-Linux-x86_64.tar.gz | tar xz)
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          /opt/cmake-3.8.0-Linux-x86_64/bin/cmake .. -G Ninja &&
          ninja

  debian_10_buster:
    docker:
      - image: debian:10-slim
    steps:
      - run: |
          apt-get update &&
          apt-get install -y --no-install-recommends cmake g++ ninja-build
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja &&
          ninja

  ubuntu_20_04:
    docker:
      - image: ubuntu:20.04
    steps:
      - run: |
          apt-get update &&
          apt-get install -y --no-install-recommends cmake g++ ninja-build
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja &&
          ninja

  fedora_32:
    docker:
      - image: fedora:32
    steps:
      - run: |
          dnf install -y git cmake gcc-c++ ninja-build
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja &&
          ninja

  arch_latest:
    docker:
      - image: archlinux/base:latest
    steps:
      - run: |
          pacman -Sy &&
          pacman -S --noconfirm cmake gcc ninja
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja &&
          ninja

  void:
    docker:
      - image: tsunagariengine/voidlinux-bash:latest
    steps:
      - run: |
          xbps-install -S &&
          xbps-install -uy xbps &&
          xbps-install -uy &&
          xbps-install -y git cmake make gcc
      - checkout
      - run: |
          git submodule update --init &&
          mkdir build &&
          cd build &&
          cmake .. &&
          make

  void_musl:
    docker:
      - image: tsunagariengine/voidlinux-musl-bash:latest
    steps:
      - run: |
          xbps-install -S &&
          xbps-install -uy xbps &&
          xbps-install -uy &&
          xbps-install -y git cmake make gcc
      - checkout
      - run: |
          git submodule update --init &&
          mkdir build &&
          cd build &&
          cmake .. &&
          make

  alpine_3_11:
    docker:
      - image: alpine:3.11
    steps:
      - run: |
          apk add git cmake make g++
      - checkout
      - run: |
          git submodule update --init &&
          mkdir build &&
          cd build &&
          cmake .. &&
          make

workflows:
  version: 2
  build_all:
    jobs:
      - debian_8_jessie
      - debian_10_buster
      - ubuntu_20_04
      - fedora_32
      - arch_latest
      - void
      - void_musl
      - alpine_3_11
