version: 2.1

jobs:
  debian_9:
    docker:
      - image: debian:9-slim
    steps:
      - run: |
          echo 'deb http://deb.debian.org/debian stretch-backports main' >> /etc/apt/sources.list &&
          apt-get update &&
          apt-get install -y --no-install-recommends git ca-certificates openssh-client cmake/stretch-backports libuv1/stretch-backports make g++
      - checkout
      - run: |
          git submodule update --init --recursive &&
          mkdir build &&
          cd build &&
          cmake .. &&
          cmake --build .

  debian_10:
    docker:
      - image: debian:10-slim
    steps:
      - run: |
          apt-get update &&
          apt-get install -y --no-install-recommends git ca-certificates cmake make g++
      - checkout
      - run: |
          git submodule update --init --recursive &&
          mkdir build &&
          cd build &&
          cmake .. &&
          cmake --build .

  ubuntu_19_10:
    docker:
      - image: ubuntu:19.10
    steps:
      - run: |
          apt-get update &&
          apt-get install -y --no-install-recommends git ca-certificates cmake make g++
      - checkout
      - run: |
          git submodule update --init --recursive &&
          mkdir build &&
          cd build &&
          cmake .. &&
          cmake --build .

  fedora_31:
    docker:
      - image: fedora:31
    steps:
      - run: |
          dnf install -y git cmake make gcc-c++
      - checkout
      - run: |
          git submodule update --init --recursive &&
          mkdir build &&
          cd build &&
          cmake .. &&
          cmake --build .

  arch_latest:
    docker:
      - image: archlinux/base:latest
    steps:
      - run: |
          pacman -Sy &&
          pacman -S --noconfirm git cmake make gcc
      - checkout
      - run: |
          git submodule update --init --recursive &&
          mkdir build &&
          cd build &&
          cmake .. &&
          cmake --build .

  void:
    docker:
      - image: tsunagariengine/voidlinux-bash:latest
    steps:
      - run: |
          xbps-install -S &&
          xbps-install -uy &&
          xbps-install -uy &&
          xbps-install -y git cmake make gcc
      - checkout
      - run: |
          git submodule update --init --recursive &&
          mkdir build &&
          cd build &&
          cmake .. &&
          cmake --build .

  void_musl:
    docker:
      - image: tsunagariengine/voidlinux-musl-bash:latest
    steps:
      - run: |
          xbps-install -S &&
          xbps-install -uy &&
          xbps-install -uy &&
          xbps-install -y git cmake make gcc
      - checkout
      - run: |
          git submodule update --init --recursive &&
          mkdir build &&
          cd build &&
          cmake .. &&
          cmake --build .

  alpine_3_10_1:
    docker:
      - image: alpine:3.10.1
    steps:
      - run: |
          apk add git cmake make g++
      - checkout
      - run: |
          git submodule update --init --recursive &&
          mkdir build &&
          cd build &&
          cmake .. &&
          cmake --build .

workflows:
  version: 2
  build_all:
    jobs:
      - debian_9
      - debian_10
      - ubuntu_19_10
      - fedora_31
      - arch_latest
      - void
      - void_musl
      - alpine_3_10_1
