version: 2.1

jobs:
  debian_9_9:
    docker:
      - image: debian:9.9-slim
    steps:
      - run: |
          echo 'deb http://deb.debian.org/debian stretch-backports main' >> /etc/apt/sources.list &&
          apt-get update &&
          apt-get install -y git cmake/stretch-backports libuv1/stretch-backports make g++
      - checkout
      - run: |
          git submodule update --init --recursive &&
          mkdir build &&
          cd build &&
          cmake .. &&
          cmake --build .

  ubuntu_19_04:
    docker:
      - image: ubuntu:19.04
    steps:
      - run: |
          apt-get update &&
          apt-get install -y git cmake make g++
      - checkout
      - run: |
          git submodule update --init --recursive &&
          mkdir build &&
          cd build &&
          cmake .. &&
          cmake --build .

  fedora_29:
    docker:
      - image: fedora:29
    steps:
      - run: |
          dnf install -y git cmake make gcc-c++
      - checkout
      - run: |
          git submodule update --init --recursive &&
          mkdir build &&
          cd build &&
          cmake .. &&
          cmake --build .

  arch_latest:
    docker:
      - image: archlinux/base:latest
    steps:
      - run: |
          pacman -Sy &&
          pacman -S --noconfirm git cmake make gcc
      - checkout
      - run: |
          git submodule update --init --recursive &&
          mkdir build &&
          cd build &&
          cmake .. &&
          cmake --build .

  void:
    docker:
      - image: pmerrill/voidlinux-bash:latest
    steps:
      - run: |
          xbps-install -S &&
          xbps-install -uy &&
          xbps-install -uy &&
          xbps-install -y git cmake make gcc
      - checkout
      - run: |
          git submodule update --init --recursive &&
          mkdir build &&
          cd build &&
          cmake .. &&
          cmake --build .

  alpine_3_10:
    docker:
      - image: alpine:3.10
    steps:
      - run: |
          apk add git cmake make g++
      - checkout
      - run: |
          git submodule update --init --recursive &&
          mkdir build &&
          cd build &&
          cmake .. &&
          cmake --build .

workflows:
  version: 2
  build_all:
    jobs:
      - debian_9_9
      - ubuntu_19_04
      - fedora_29
      - arch_latest
      - void
      - alpine_3_10
