version: 2.1

jobs:
  debian_9:
    docker:
      - image: debian:9-slim
    steps:
      - run: |
          echo 'deb http://deb.debian.org/debian stretch-backports main' >> /etc/apt/sources.list &&
          apt-get update &&
          apt-get install -y --no-install-recommends git ca-certificates openssh-client libuv1/stretch-backports make g++ &&
          apt-get install -y --no-install-recommends libarchive13 cmake-data/stretch-backports libcurl3 libjsoncpp1 librhash0 &&
          (apt-get download cmake/stretch-backports || true) &&
          dpkg --force-all -i cmake*.deb &&
          rm cmake*.deb
      - checkout
      - run: |
          git submodule update --init &&
          mkdir build &&
          cd build &&
          cmake .. &&
          make

  debian_10:
    docker:
      - image: debian:10-slim
    steps:
      - run: |
          apt-get update &&
          apt-get install -y --no-install-recommends git ca-certificates cmake make g++
      - checkout
      - run: |
          git submodule update --init &&
          mkdir build &&
          cd build &&
          cmake .. &&
          make

  ubuntu_19_10:
    docker:
      - image: ubuntu:19.10
    steps:
      - run: |
          apt-get update &&
          apt-get install -y --no-install-recommends git ca-certificates cmake make g++
      - checkout
      - run: |
          git submodule update --init &&
          mkdir build &&
          cd build &&
          cmake .. &&
          make

  fedora_31:
    docker:
      - image: fedora:31
    steps:
      - run: |
          dnf install -y git cmake make gcc-c++
      - checkout
      - run: |
          git submodule update --init &&
          mkdir build &&
          cd build &&
          cmake .. &&
          make

  arch_latest:
    docker:
      - image: archlinux/base:latest
    steps:
      - run: |
          pacman -Sy &&
          pacman -S --noconfirm git cmake make gcc
      - checkout
      - run: |
          git submodule update --init &&
          mkdir build &&
          cd build &&
          cmake .. &&
          make

  void:
    docker:
      - image: tsunagariengine/voidlinux-bash:latest
    steps:
      - run: |
          xbps-install -S &&
          xbps-install -uy xbps &&
          xbps-install -uy &&
          xbps-install -y git cmake make gcc
      - checkout
      - run: |
          git submodule update --init &&
          mkdir build &&
          cd build &&
          cmake .. &&
          make

  void_musl:
    docker:
      - image: tsunagariengine/voidlinux-musl-bash:latest
    steps:
      - run: |
          xbps-install -S &&
          xbps-install -uy xbps &&
          xbps-install -uy &&
          xbps-install -y git cmake make gcc
      - checkout
      - run: |
          git submodule update --init &&
          mkdir build &&
          cd build &&
          cmake .. &&
          make

  alpine_3_11:
    docker:
      - image: alpine:3.11
    steps:
      - run: |
          apk add git cmake make g++
      - checkout
      - run: |
          git submodule update --init &&
          mkdir build &&
          cd build &&
          cmake .. &&
          make

workflows:
  version: 2
  build_all:
    jobs:
      - debian_9
      - debian_10
      - ubuntu_19_10
      - fedora_31
      - arch_latest
      - void
      - void_musl
      - alpine_3_11
