version: 2.1

jobs:
  # Has CMake 3.0, GCC 4.8
  alpine_3_1:
    docker:
      - image: alpine:3.1
    steps:
      - run: |
          apk update &&
          apk add cmake g++ make
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -DCMAKE_BUILD_TYPE=Debug &&
          make -j `grep processor /proc/cpuinfo | wc -l`
      - run: build/test

  # Has CMake 3.18, GCC 10, Samurai 1.2
  alpine_3_13:
    docker:
      - image: alpine:3.13
    steps:
      - run: |
          apk update &&
          apk add cmake g++ samurai
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
          samu
      - run: build/test

  arch:
    docker:
      - image: archlinux/base:latest
    steps:
      - run: |
          pacman -Sy --noconfirm cmake gcc samurai
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
          samu
      - run: build/test

  # Has CMake 2.8.12, GCC 4.8
  centos_7:
    docker:
      - image: centos:7
    steps:
      - run: |
          yum install -y cmake gcc-c++ make
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -DCMAKE_BUILD_TYPE=Debug &&
          make -j `grep processor /proc/cpuinfo | wc -l`
      - run: build/test

  # Has CMake 3.11, GCC 8
  centos_8:
    docker:
      - image: centos:8
    steps:
      - run: |
          dnf install -y cmake gcc-c++ make
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -DCMAKE_BUILD_TYPE=Debug &&
          make -j `grep processor /proc/cpuinfo | wc -l`
      - run: build/test

  # Has CMake 3.0, GCC 4.9
  debian_8_jessie:
    docker:
      - image: debian:8-slim
    steps:
      - run: |
          apt-get update &&
          apt-get install -y --no-install-recommends cmake g++ ninja-build
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
          ninja
      - run: build/test

  # Has CMake 3.13, GCC 8
  debian_10_buster:
    docker:
      - image: debian:10-slim
    steps:
      - run: |
          apt-get update &&
          apt-get install -y --no-install-recommends cmake g++ ninja-build
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
          ninja
      - run: build/test

  # Has CMake 2.8.12, GCC 4.8, Ninja 1.4
  fedora_20:
    docker:
      - image: fedora:20
    steps:
      - run: |
          yum install -y cmake gcc-c++ ninja-build
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
          ninja-build
      - run: build/test

  # Has CMake 3.18, GCC 10, Ninja 1.10
  fedora_33:
    docker:
      - image: fedora:33
    steps:
      - run: |
          dnf install -y cmake gcc-c++ ninja-build
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
          ninja
      - run: build/test

  # Has CMake 3.3, GCC 4.9, Ninja 1.6
  #nix_1_1_0:
  #  shell: /bin/sh
  #  docker:
  #    - image: nixos/nix:1.1.0
  #  steps:
  #    - checkout
  #    - run: |
  #        nix-env -i bash &&
  #        mkdir build &&
  #        cd build &&
  #        nix-shell -p cmake gcc ninja --run 'cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug && ninja && ./test'

  # Has CMake 3.17, GCC 9.3, Samurai 1.1
  nix_2_3_6:
    shell: /bin/sh
    docker:
      - image: nixos/nix:2.3.6
    steps:
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          nix-shell -p cmake gcc samurai --run 'cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug && samu && ./test'

  # Has CMake 2.8.12, GCC 4.9, Ninja 1.3
  ubuntu_14_04_trusty:
    docker:
      - image: ubuntu:14.04
    steps:
      - run: |
          apt-get update &&
          apt-get install -y --no-install-recommends cmake g++ ninja-build
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
          ninja
      - run: build/test

  # Has CMake 3.16, GCC 10, Ninja 1.10
  ubuntu_20_10_groovy:
    docker:
      - image: ubuntu:20.10
    steps:
      - run: |
          apt-get update &&
          apt-get install -y --no-install-recommends cmake g++ ninja-build
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
          ninja
      - run: build/test

  void:
    shell: /bin/sh
    docker:
      - image: voidlinux/voidlinux:latest
    steps:
      - run: |
          xbps-install -Suy xbps &&
          xbps-install -y bash cmake gcc samurai
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
          samu
      - run: build/test

  void_musl:
    shell: /bin/sh
    docker:
      - image: voidlinux/voidlinux-musl:latest
    steps:
      - run: |
          xbps-install -Suy xbps &&
          xbps-install -y cmake gcc samurai
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
          samu
      - run: build/test

workflows:
  version: 2
  build_all:
    jobs:
      - alpine_3_1
      - alpine_3_13
      - arch
      - centos_7
      - centos_8
      - debian_8_jessie
      - debian_10_buster
      - fedora_20
      - fedora_33
      - nix_2_3_6
      - ubuntu_14_04_trusty
      - ubuntu_20_10_groovy
      - void
      - void_musl
