version: 2.1

jobs:
  # Has CMake 3.0, GCC 4.8
  alpine_3_1:
    docker:
      - image: alpine:3.1
    steps:
      - run: |
          apk update &&
          apk add cmake g++ make
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -DCMAKE_BUILD_TYPE=Debug &&
          make -j 2
      - run: build/units

  # Has CMake 3.20, GCC 10, Samurai 1.2
  alpine_3_14:
    docker:
      - image: alpine:3.14
    steps:
      - run: |
          apk update &&
          apk add cmake g++ samurai
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
          samu
      - run: build/units

  arch:
    docker:
      - image: archlinux
    steps:
      - run: |
          patched_glibc=glibc-linux4-2.33-4-x86_64.pkg.tar.zst && \
          curl -LO https://repo.archlinuxcn.org/x86_64/"$patched_glibc" && \
          bsdtar -C / -xvf "$patched_glibc" &&
          rm "$patched_glibc"
          pacman -Sy --noconfirm cmake gcc samurai
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
          samu
      - run: build/units

  # Has CMake 2.8.12, GCC 4.8
  centos_7:
    docker:
      - image: centos:7
    steps:
      - run: |
          yum install -y cmake gcc-c++ make
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -DCMAKE_BUILD_TYPE=Debug &&
          make -j 2
      - run: build/units

  # Has CMake 3.11, GCC 8
  centos_8:
    docker:
      - image: centos:8
    steps:
      # Install libarchive to solve a build issue due to CMake/libarchive
      # version mismatch on CentOS 8. (2021-06-20)
      - run: |
          dnf install -y cmake gcc-c++ libarchive make
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -DCMAKE_BUILD_TYPE=Debug &&
          make -j 2
      - run: build/units

  # Has CMake 2.8.9, GCC 4.7
  debian_7_wheezy:
    docker:
      - image: debian:7-slim
    steps:
      - run: |
          dpkg -l &&
          echo 'deb http://archive.debian.org/debian wheezy main' > /etc/apt/sources.list &&
          apt-get update &&
          apt-get install -y --no-install-recommends --force-yes cmake g++ libc6=2.13-38+deb7u10 libc-bin=2.13-38+deb7u10 make
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -DCMAKE_BUILD_TYPE=Debug &&
          make -j 2
      - run: build/units

  # Has CMake 3.18, GCC 10, Ninja 1.10
  debian_11_bullseye:
    docker:
      - image: debian:bullseye-slim
    steps:
      - run: |
          apt-get update &&
          apt-get install -y --no-install-recommends cmake g++ ninja-build
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
          ninja
      - run: build/units

  # Has CMake 2.8.12, GCC 4.8, Ninja 1.4
  fedora_20:
    docker:
      - image: fedora:20
    steps:
      - run: |
          yum install -y cmake gcc-c++ ninja-build
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
          ninja-build
      - run: build/units

  # Has CMake 3.20, GCC 11, Ninja 1.10
  fedora_34:
    docker:
      - image: fedora:34
    steps:
      - run: |
          dnf install -y cmake gcc-c++ samurai
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
          samu
      - run: build/units

  # Has CMake 3.3, GCC 4.9, Ninja 1.6
  #nix_1_1_0:
  #  shell: /bin/sh
  #  docker:
  #    - image: nixos/nix:1.1.0
  #  steps:
  #    - checkout
  #    - run: |
  #        nix-env -i bash &&
  #        mkdir build &&
  #        cd build &&
  #        nix-shell -p cmake gcc ninja --run 'cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug && ninja && ./units'

  # Has CMake 3.19, GCC 10, Samurai 1.2
  nix_2_3_12:
    shell: /bin/sh
    docker:
      - image: nixos/nix:2.3.12
    steps:
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          nix-shell -p cmake gcc samurai --run 'cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug && samu && ./units'

  # Has CMake 2.8.7, GCC 4.6
  ubuntu_12_04_precise:
    docker:
      - image: ubuntu:precise
    steps:
      - run: |
          echo 'deb http://old-releases.ubuntu.com/ubuntu precise main' > /etc/apt/sources.list &&
          apt-get update &&
          apt-get install -y --no-install-recommends --force-yes cmake g++ libc6=2.15-0ubuntu10 libc-bin=2.15-0ubuntu10 make
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -DCMAKE_BUILD_TYPE=Debug &&
          make -j 2
      - run: build/units

  # Has CMake 3.18, GCC 10, Ninja 1.10
  ubuntu_21_04_hirsute:
    docker:
      - image: ubuntu:21.04
    steps:
      - run: |
          apt-get update &&
          apt-get install -y --no-install-recommends cmake g++ ninja-build
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
          ninja
      - run: build/units

  void:
    shell: /bin/sh
    docker:
      - image: voidlinux/voidlinux:latest
    steps:
      - run: |
          xbps-install -Suy xbps &&
          xbps-install -y bash cmake gcc samurai
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
          samu
      - run: build/units

  void_musl:
    shell: /bin/sh
    docker:
      - image: voidlinux/voidlinux-musl:latest
    steps:
      - run: |
          xbps-install -Suy xbps &&
          xbps-install -y cmake gcc samurai
      - checkout
      - run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug &&
          samu
      - run: build/units

workflows:
  version: 2
  build_all:
    jobs:
      - alpine_3_1
      - alpine_3_14
      - arch
      - centos_7
      - centos_8
      - debian_7_wheezy
      - debian_11_bullseye
      - fedora_20
      - fedora_34
      - nix_2_3_12
      - ubuntu_12_04_precise
      - ubuntu_21_04_hirsute
      - void
      - void_musl
