name: Build

on: [push]

jobs:
  macos_11_0_big_sur:
    name: macOS 11.0 Big Sur
    runs-on: macos-11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          curl -LOsS https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-mac.zip
          unzip ninja-mac.zip >/dev/null && rm ninja-mac.zip
          PATH=$PATH:$PWD
          mkdir build
          cd build
          cmake .. -G Ninja
          ninja
