# https://github.com/actions/runner-images

name: Build

on: [push]

jobs:
  macos_13_ventura:
    name: macOS 13 Ventura
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          PATH=$PATH:$PWD
          mkdir build
          cd build
          cmake .. -G Xcode -DUNITS=1
          cmake --build .
      - name: Test
        run: build/Debug/units
