name: Build

on: [push]

jobs:
  macos_11_0_big_sur:
    name: macOS 11.0 Big Sur
    runs-on: macos-11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          PATH=$PATH:$PWD
          mkdir build
          cd build
          cmake .. -G Xcode
          cmake --build .
      - name: Test
        run: build/units
