# https://github.com/actions/virtual-environments

name: Build

on: [push]

jobs:
  macos_12_monterey:
    name: macOS 12 Monterey
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          PATH=$PATH:$PWD
          mkdir build
          cd build
          cmake .. -G Xcode
          cmake --build .
      - name: Test
        run: build/Debug/units
